add get order method
mholt/acmez pull request #9
Opened 2022-03-05 11:29 UTC by mailbaoer

I want make an api service for cert request for those who want get certificate use dns TXT records manually, like this steps:
1. send request and return txt records
2. add txt records manually from their dns servers
3. solve the challenge
4. get certificate
If we do not have a get order method, we can't get the order  created from step 1, these will create a lot of invalid new orders, so I want to add a get order method, we just need to set the order's Location. Hope to be merged. I have tested that method works!

2022-03-05 23:40 UTC, mholt commented
Hi, thanks for this contribution.

I want to make sure I understand the need for this though. Don't you get the order returned when you call `NewOrder()`?

2022-03-06 02:21 UTC, mailbaoer commented
ok, I will give my test code:
```go
var ids []acme.Identifier
	for _, domain := range domains {
		ids = append(ids, acme.Identifier{Type: "dns", Value: domain})
	}
	order := acme.Order{Identifiers: ids}
	order, err = client.NewOrder(ctx, account, order)
	if err != nil {
		return fmt.Errorf("creating new order err: %v", err)
	}
	fmt.Println("Order create result:", order.Location)

	order = acme.Order{Identifiers: ids, Location: "https://acme-staging-v02.api.letsencrypt.org/acme/order/xxxx/1947985738"} // xxx I replaced
	order, err = client.GetOrder(ctx, account, order)
	if err != nil {
		return fmt.Errorf("getting new order err: %v", err)
	}
	fmt.Println("Order get result:", order.Location)
```
and I can get the result
![screenshot-20220306-101807](https://user-images.githubusercontent.com/5282978/156906390-2e8ea6db-e9e0-4f0d-8136-8f872083c8a4.png)

From the screenshot we can see that, `NewOrder` method will create new order every time, `GetOrder` method can return the given location of the order

2022-03-06 02:25 UTC, francislavoie commented
I think Matt's question is "why do you need to get it again later, at all?" Why can't you just cache the order you get from `NewOrder` in some map if you need to reuse it?

2022-03-06 02:30 UTC, mailbaoer commented
oh, I just explained in the first, I want to make an api service, someone can submit a request, then I will record the txt records he need to add on their dns servers later, when confirmed the records added, they can send another request to solve the challenge

2022-03-06 02:33 UTC, francislavoie commented
Well, the order is just a struct with no unexported fields. Why can't you just store it somewhere in the meantime? Serialize it to JSON for example, write it to a database or to file.

2022-03-06 02:46 UTC, mailbaoer commented
Yes, you are right, I've already do that, but like `https://github.com/mholt/acmez/blob/master/examples/plumbing/main.go#L114`,when I want to get the latest order authentications or Challenges status, I must get the order latest status first. If we send the request to solve the challenges, it may take It will take a few minutes, like `https://github.com/mholt/acmez/blob/master/examples/plumbing/main.go#L144`, it will polling loop for check authentications, if we can get the latest order status, we just need to send a request, no need polling.

2022-03-06 02:47 UTC, mailbaoer commented
Another motivation is that I use godaddy's dns nameserver, and the minimum txt records time can only be set to 6000 seconds. If we go to solve channellege immediately, it is easy to cause letsencrypt to not be able to query the correct txt records, so I'd better wait After 600 seconds, I will go to the query. If there is an interface to query the order, then I can do other things in these 600 seconds.

2022-03-06 04:05 UTC, mholt commented
Hm, that is a unique flow. I guess having a getter method doesn't hurt. The spec even says:

>    Clients SHOULD check the "status" field of an order to determine
>   whether they need to take any action.

So, having the ability to read the current status of an order could be useful to some.

2022-03-06 04:06 UTC, mholt requested changes
Thanks, just a couple of nitpicks.

2022-03-06 04:06 UTC, mholt commented on acme/order.go
> +// GetOrder get a order with the server.
```suggestion
// GetOrder retrieves an order from the server. The Order's Location field must be populated.
```

2022-03-06 04:06 UTC, mholt commented on acme/order.go
> +// request to the server's order resource." §7.4
```suggestion
```

I don't think this part of the spec is relevant.

2022-03-06 04:39 UTC, mailbaoer commented
Thank you for your advise,I've already changed!

2022-03-06 17:24 UTC, mholt commented on acme/order.go
> +	return order, nil
```suggestion
	return order, err
```

Just realized we could simplify this more

2022-03-06 17:25 UTC, mholt approved these changes
Thanks for the contribution!

2022-03-06 17:26 UTC, merged